package com.example.dogetime.util.extractors.dailymotion.models

data class DailymotionDTO(
    val access_id: String,
    val channel: String,
    val consent: Consent,
    val created_time: Int,
    val data_center: String,
    val detected_language: String,
    val duration: Int,
    val explicit: Boolean,
    val filmstrip_url: String,
    val id: String,
    val info: Info,
    val is_created_for_kids: Boolean,
    val is_password_protected: Boolean,
    val language: String,
    val live_show_viewers: Boolean,
    val media_type: String,
    val mode: String,
    val owner: Owner,
    val partner: Boolean,
    val player_owner: PlayerOwner,
    val posters: Posters,
    val `private`: Boolean,
    val protected_delivery: Boolean,
    val qualities: Qualities,
    val seeker_url: String,
    val sharing: List<Sharing>,
    val stream_type: String,
    val subtitles: Subtitles,
    val tags: List<Any>,
    val title: String,
    val ui: Ui,
    val url: String,
    val verified: Boolean,
    val view_id: String
)