package com.example.kotlinmovieapp.util.extractors.vidplay.models

data class Blob(
    val csv: Any,
    val csvError: Any,
    val dependabotInfo: Any,
    val discussionTemplate: Any,
    val displayName: String,
    val displayUrl: String,
    val headerInfo: Any,
    val image: Boolean,
    val isCodeownersFile: Any,
    val isPlain: Boolean,
    val isValidLegacyIssueTemplate: Boolean,
    val issueTemplate: Any,
    val issueTemplateHelpUrl: String,
    val language: String,
    val languageID: Int,
    val large: Boolean,
    val loggedIn: Boolean,
    val planSupportInfo: Any,
    val publishBannersInfo: Any,
    val rawBlobUrl: String,
    val rawLines: List<String>,
    val renderImageOrRaw: Boolean,
    val renderedFileInfo: Any,
    val richText: Any,
    val shortPath: Any,
    val stylingDirectives: List<List<Any>>,
    val symbols: Any,
    val symbolsEnabled: Boolean,
    val tabSize: Int,
    val topBannersInfo: Any,
    val truncated: Boolean,
    val viewable: Boolean,
    val workflowRedirectUrl: Any
)